export const backendCurriculum = [
 ['C# foundations', 'C# types: value/reference semantics, boxing and nullable values'],
 ['C# foundations', 'Classes, records, structs, properties and access modifiers'],
 ['C# foundations', 'OOP principles'],
 ['C# foundations', 'Interfaces, abstract classes, composition and polymorphism'],
 ['C# foundations', 'SOLID principles and pragmatic design patterns'],
 ['C# foundations', 'Generics, collections, dictionaries and complexity'],
 ['C# foundations', 'LINQ: filtering, grouping, joins and deferred execution'],
 ['C# foundations', 'IEnumerable versus IQueryable and query execution boundaries'],
 ['C# foundations', 'Exceptions, custom errors and reliable cleanup'],
 ['C# foundations', 'Async/await, Task, cancellation and avoiding blocking calls'],
 ['C# foundations', 'Garbage collection, IDisposable, using and resource lifetimes'],
 ['ASP.NET Core', '.NET request lifecycle'],
 ['ASP.NET Core', 'Hosting, Program.cs, service registration and environment settings'],
 ['ASP.NET Core', 'Middleware ordering, short circuits and exception handling'],
 ['ASP.NET Core', 'Dependency injection'],
 ['ASP.NET Core', 'Singleton, scoped and transient lifetimes; captive dependencies'],
 ['ASP.NET Core', 'Configuration, options validation and secret management'],
 ['ASP.NET Core', 'Controllers versus minimal APIs; routing and endpoint conventions'],
 ['ASP.NET Core', 'Model binding, validation, DTOs and serialization'],
 ['ASP.NET Core', 'REST design: resources, HTTP methods, status codes and idempotency'],
 ['ASP.NET Core', 'Pagination, filtering, sorting and API contracts'],
 ['ASP.NET Core', 'Problem Details, global errors and structured logging'],
 ['ASP.NET Core', 'Authentication: cookies, bearer tokens and OpenID Connect concepts'],
 ['ASP.NET Core', 'Authorization: policies, claims and object-level access checks'],
 ['ASP.NET Core', 'API security: input validation, CORS, CSRF and rate limiting'],
 ['EF Core', 'Relational foundations: keys, relationships, constraints and indexes'],
 ['EF Core', 'DbContext, DbSet, providers and scoped context lifetime'],
 ['EF Core', 'Entity mapping: conventions, annotations and Fluent API'],
 ['EF Core', 'Relationships: one-to-one, one-to-many and many-to-many'],
 ['EF Core', 'Migrations, schema evolution, rollback and production deployment'],
 ['EF Core', 'Change tracking, entity states, SaveChanges and no-tracking queries'],
 ['EF Core', 'LINQ translation, projection, generated SQL and parameterization'],
 ['EF Core', 'Related data: eager, explicit and lazy loading; N+1 queries'],
 ['EF Core', 'Query performance: indexes, split queries and keyset pagination'],
 ['EF Core', 'Transactions, isolation and multiple SaveChanges calls'],
 ['EF Core', 'Optimistic concurrency tokens and conflict resolution'],
 ['EF Core', 'Async data access, cancellation and avoiding parallel DbContext use'],
 ['GraphQL', 'GraphQL versus REST: schema contracts and tradeoffs'],
 ['GraphQL', 'Schema types: scalars, objects, enums, inputs, lists and nullability'],
 ['GraphQL', 'Queries, mutations, variables, fragments and aliases'],
 ['GraphQL', 'Resolvers, execution, field errors and null propagation'],
 ['GraphQL', 'DataLoader batching, N+1 prevention and EF Core integration'],
 ['GraphQL', 'Authentication and field/resource-level authorization'],
 ['Production practices', 'Unit and integration tests; API hosting and real database behavior'],
 ['Interview practice', 'Build a validated CRUD API with EF Core and integration tests'],
 ['Interview practice', 'Add authentication, authorization, pagination and consistent errors'],
 ['Interview practice', 'Expose a GraphQL query and mutation without N+1 database access'],
 ['Interview practice', 'Debug a slow query, concurrency conflict and dependency lifetime bug'],
 ['Interview practice', 'Explain API architecture, performance and security tradeoffs aloud'],
] as const;
