export const databaseCurriculum = [
 ['Relational foundations', 'Tables, schemas, primary/foreign keys and integrity constraints'],
 ['Relational foundations', 'Normalization through 3NF and pragmatic denormalization'],
 ['Relational foundations', 'SQL Server data types, NULL semantics and three-valued logic'],
 ['T-SQL essentials', 'SELECT, WHERE, ORDER BY, TOP and logical query processing order'],
 ['T-SQL essentials', 'SQL joins: INNER, LEFT, RIGHT, FULL, CROSS and self joins'],
 ['T-SQL essentials', 'GROUP BY, HAVING, aggregates and conditional aggregation'],
 ['T-SQL essentials', 'Subqueries, correlated subqueries, EXISTS and NOT EXISTS'],
 ['T-SQL essentials', 'CTEs, derived tables, temporary tables and table variables'],
 ['T-SQL essentials', 'Window functions: ROW_NUMBER, RANK, DENSE_RANK, LAG and LEAD'],
 ['Database objects', 'Views, stored procedures, parameters and user-defined function tradeoffs'],
 ['Performance', 'Indexes: clustered/nonclustered, composite keys and included columns'],
 ['Performance', 'Execution plans: seeks/scans, joins, key lookups and statistics'],
 ['Performance', 'SARGable predicates, covering indexes and diagnosing slow queries'],
 ['Transactions', 'Transactions: ACID, BEGIN/COMMIT/ROLLBACK and XACT_ABORT'],
 ['Transactions', 'Isolation levels, dirty/nonrepeatable/phantom reads and row versioning'],
 ['Transactions', 'Blocking, deadlocks, short transactions and retry tradeoffs'],
 ['Application integration', 'Parameterized queries, SQL injection prevention and least privilege'],
 ['Interview practice', 'Solve duplicates, nth-highest salary, top-per-group and running totals'],
] as const;
