export const frontendCurriculum = [
 ['Web foundations', 'How browsers work: requests, DOM, CSSOM, rendering and reflow'],
 ['Web foundations', 'Semantic HTML: landmarks, headings, links and document structure'],
 ['Web foundations', 'Forms: labels, input types, validation and submission'],
 ['Web foundations', 'Accessibility: keyboard navigation, focus, screen readers and ARIA'],
 ['Web foundations', 'CSS cascade, specificity, inheritance and the box model'],
 ['Web foundations', 'CSS layouts: Flexbox, Grid, positioning and stacking contexts'],
 ['Web foundations', 'Responsive design: mobile layouts, media queries and fluid sizing'],
 ['Web foundations', 'Browser networking: HTTP, HTTPS, status codes, caching and CORS'],
 ['JavaScript', 'Values, types, coercion, equality, variables and immutability'],
 ['JavaScript', 'Scope, hoisting, closures and the temporal dead zone'],
 ['JavaScript', 'Functions, arrow functions, this, call, apply and bind'],
 ['JavaScript', 'Objects, prototypes, classes and composition'],
 ['JavaScript', 'Arrays: map, filter, reduce, sorting and complexity'],
 ['JavaScript', 'Destructuring, spread, rest, optional chaining and nullish coalescing'],
 ['JavaScript', 'DOM manipulation, event propagation and event delegation'],
 ['JavaScript', 'Event loop: call stack, tasks, microtasks and timers'],
 ['JavaScript', 'Promises, async/await, error handling and concurrent requests'],
 ['JavaScript', 'Fetch, JSON, request cancellation and stale-response handling'],
 ['JavaScript', 'Modules, browser storage, cookies and memory cleanup'],
 ['TypeScript', 'Type inference, annotations, unions, literals and narrowing'],
 ['TypeScript', 'Interfaces, type aliases, optional fields and readonly data'],
 ['React', 'Components and JSX'],
 ['React', 'Props and state'],
 ['React', 'Event handling'],
 ['React', 'Conditional rendering'],
 ['React', 'Lists and keys'],
 ['React', 'Forms and validation'],
 ['React', 'Immutable array and object updates'],
 ['React', 'Sharing state, derived state and a single source of truth'],
 ['React', 'useState and useEffect'],
 ['React', 'Effect dependencies, cleanup, Strict Mode and avoiding unnecessary effects'],
 ['React', 'Refs: DOM access and values that do not trigger renders'],
 ['React', 'Custom hooks'],
 ['React', 'Context and state management'],
 ['React', 'Routing'],
 ['React', 'API calls and async handling'],
 ['React', 'Loading, empty and error states; retries and error boundaries'],
 ['React', 'Performance: profiling, memoization, code splitting and virtualization'],
 ['React', 'Testing and accessibility'],
 ['Angular essentials', 'Standalone components, templates and component metadata'],
 ['Angular essentials', 'Property and event binding, inputs, outputs and template control flow'],
 ['Angular essentials', 'Services, dependency injection and inject'],
 ['Angular essentials', 'Reactive forms, validation and form state'],
 ['Angular essentials', 'Router, lazy loading, route guards and HttpClient'],
 ['Coding practices', 'Readable code: naming, small functions and clear responsibilities'],
 ['Coding practices', 'Linting, formatting, strict typing and code review'],
 ['Coding practices', 'Unit, integration and end-to-end tests; mock network boundaries'],
 ['Coding practices', 'Debugging with browser tools and React/Angular devtools'],
 ['Coding practices', 'Security: XSS, CSRF, safe HTML, authentication and client-side secrets'],
 ['Coding practices', 'Performance: bundle size, lazy assets, caching and Core Web Vitals'],
 ['Interview practice', 'Build a small typed React app with routing, API integration and tests'],
 ['Interview practice', 'Explain architecture, tradeoffs and debug a broken component aloud'],
] as const;
